using UnivueGuardian.Models;

namespace UnivueGuardian.Core;

public class ReportGenerator
{
    public string GenerateWeeklyHtml(
        List<ServerMetrics>   metricsHistory,
        List<AlertEntry>      alerts,
        List<MonitoredService> services,
        List<MonitoredDomain>  domains)
    {
        var now      = DateTime.Now;
        var weekAgo  = now.AddDays(-7);
        var weekAlerts = alerts.Where(a => a.Time >= weekAgo).ToList();

        double avgCpu    = metricsHistory.Any() ? metricsHistory.Average(m => m.CpuPercent) : 0;
        double maxCpu    = metricsHistory.Any() ? metricsHistory.Max(m => m.CpuPercent)     : 0;
        double avgRam    = metricsHistory.Any() ? metricsHistory.Average(m => m.RamPercent)  : 0;
        int    critCount = weekAlerts.Count(a => a.Severity == AlertSeverity.Critical);
        int    warnCount = weekAlerts.Count(a => a.Severity == AlertSeverity.Warning);

        var svcRows = string.Concat(services.Select(s =>
            $"<tr><td>{s.DisplayName}</td>" +
            $"<td style='color:{(s.Status == ServiceStatus.Running ? "#2e7d32" : "#c62828")}'>{s.Status}</td>" +
            $"<td>{s.RestartCount}</td></tr>"));

        var domainRows = string.Concat(domains.Select(d =>
            $"<tr><td>{d.DisplayName}</td>" +
            $"<td>{d.Uptime24h}%</td>" +
            $"<td>{d.SslDaysRemaining}d</td>" +
            $"<td>{d.ResponseMs}ms</td></tr>"));

        var alertRows = string.Concat(weekAlerts.Take(30).Select(a =>
            $"<tr><td>{a.Time:MM-dd HH:mm}</td>" +
            $"<td style='color:{(a.Severity == AlertSeverity.Critical ? "#c62828" : "#e65100")}'>{a.Severity}</td>" +
            $"<td>{a.Source}</td>" +
            $"<td>{a.Message}</td></tr>"));

        return $@"
        <!DOCTYPE html>
        <html>
        <head>
        <meta charset='utf-8'>
        <style>
          body {{ font-family: Segoe UI, sans-serif; margin: 0; background: #f5f5f5; color: #333; }}
          .header {{ background: linear-gradient(135deg,#1a237e,#283593); color:#fff; padding:32px 40px; }}
          .header h1 {{ margin:0; font-size:24px; }}
          .header p {{ margin:4px 0 0; opacity:.7; font-size:13px; }}
          .body {{ padding: 30px 40px; }}
          .cards {{ display:flex; gap:16px; margin-bottom:24px; }}
          .card {{ background:#fff; border-radius:8px; padding:16px 20px; flex:1; box-shadow:0 1px 4px rgba(0,0,0,.08); }}
          .card .val {{ font-size:28px; font-weight:300; margin:4px 0; }}
          .card .lbl {{ font-size:11px; color:#999; text-transform:uppercase; }}
          h2 {{ font-size:15px; color:#555; border-bottom:1px solid #eee; padding-bottom:8px; margin-top:28px; }}
          table {{ width:100%; border-collapse:collapse; font-size:13px; }}
          th {{ background:#f5f5f5; padding:8px; text-align:left; color:#777; font-weight:500; }}
          td {{ padding:7px 8px; border-bottom:1px solid #f0f0f0; }}
          .ok   {{ color:#2e7d32; font-weight:500; }}
          .crit {{ color:#c62828; font-weight:500; }}
          .warn {{ color:#e65100; font-weight:500; }}
          .footer {{ background:#f0f0f0; padding:12px 40px; font-size:11px; color:#aaa; margin-top:40px; }}
        </style>
        </head>
        <body>
        <div class='header'>
          <h1>📊 Weekly Server Health Report</h1>
          <p>Period: {weekAgo:yyyy-MM-dd} → {now:yyyy-MM-dd} &nbsp;|&nbsp; Generated: {now:HH:mm}</p>
        </div>
        <div class='body'>
          <div class='cards'>
            <div class='card'><div class='lbl'>Avg CPU</div><div class='val'>{avgCpu:F1}%</div></div>
            <div class='card'><div class='lbl'>Max CPU</div><div class='val'>{maxCpu:F1}%</div></div>
            <div class='card'><div class='lbl'>Avg RAM</div><div class='val'>{avgRam:F1}%</div></div>
            <div class='card'><div class='lbl'>Critical Alerts</div><div class='val crit'>{critCount}</div></div>
            <div class='card'><div class='lbl'>Warnings</div><div class='val warn'>{warnCount}</div></div>
            <div class='card'><div class='lbl'>Total Alerts</div><div class='val'>{weekAlerts.Count}</div></div>
          </div>

          <h2>Services</h2>
          <table><tr><th>Service</th><th>Status</th><th>Restarts</th></tr>{svcRows}</table>

          <h2>Domains</h2>
          <table><tr><th>Domain</th><th>Uptime</th><th>SSL</th><th>Response</th></tr>{domainRows}</table>

          <h2>Alert History (last 7 days)</h2>
          <table><tr><th>Time</th><th>Severity</th><th>Source</th><th>Message</th></tr>{alertRows}</table>
        </div>
        <div class='footer'>Generated by Univue Guardian v2.0 &nbsp;|&nbsp; SERVER-01</div>
        </body>
        </html>";
    }

    public async Task SaveHtmlReportAsync(string html, string filePath)
    {
        await File.WriteAllTextAsync(filePath, html);
    }

    public string GetDefaultReportPath(string type = "weekly")
    {
        var folder = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
            "UnivueGuardian", "Reports");
        Directory.CreateDirectory(folder);
        return Path.Combine(folder, $"Report_{type}_{DateTime.Now:yyyyMMdd_HHmm}.html");
    }
}
